#!/usr/bin/env python3
"""Daily digest memo — lightweight summary of last 24h of signals.

Reads signals collected in last 24 hours from SQLite.
If fewer than 3 new signals, skips.
Uses MiniMax via LiteLLM (same pattern as inference_engines/base.py).

Usage:
    python3 run_digest.py

Output: operating_memos/output/daily_digest_YYYY-MM-DD.md
"""

import sys
import json
from pathlib import Path
from datetime import datetime, timezone, timedelta

# Fixed path for crontab compatibility
sys.path.insert(0, str(Path(__file__).parent.resolve()))

from inference_engines.base import InferenceEngine
from strategic_memory.store import SignalStore
from config import get_memo_output_dir


DIGEST_PROMPT = """Generate a concise daily signal digest from the signals collected in the last 24 hours.

Date: {date}

Signals collected today ({count} total):
{signals_text}

Output EXACTLY these 3 sections — nothing else:

## Today's Top Signal
[1-2 sentences: the single most important signal today and why it matters. Be specific, not generic.]

## Signal Summary
[Bullet list — one line per signal: source tag + title + 1-line interpretation of why it matters for growth/fintech/ops]

## Watch List
[3-5 things to keep an eye on based on today's signals. Brief bullets. Things that could become actionable tomorrow or this week.]

---
Generated by Growth Workflow OS Daily Digest
"""


class DailyDigestEngine(InferenceEngine):
    """Generate a lightweight daily digest via MiniMax."""

    def __init__(self):
        super().__init__("memo_generation")

    def run(self, signals: list[dict], output_path: Path) -> str:
        """Generate daily digest.

        Args:
            signals: List of signal dicts from SignalStore
            output_path: Where to write the output

        Returns:
            Path to generated file as string
        """
        # Build signals text
        lines = []
        for s in signals:
            source = s.get("source", "unknown")
            text = s.get("text", "")[:200]
            weight = s.get("strategic_weight")
            tag = f"[{weight:.0%}]" if weight else ""
            lines.append(f"- {tag} [{source}] {text}")
        signals_text = "\n".join(lines) if lines else "No signals today."

        prompt = DIGEST_PROMPT.format(
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            count=len(signals),
            signals_text=signals_text,
        )

        system_note = (
            "You are writing a daily signal digest for a fintech growth operator. "
            "Be brief, specific, and actionable. No filler. Use concrete details from the signals."
        )

        memo_text = self.infer(prompt, system_prompt=system_note)

        # MiniMax sometimes wraps in JSON — unwrap if so
        memo_text = _unwrap_json(memo_text)

        output_path.write_text(memo_text)
        return str(output_path)


def _unwrap_json(text: str) -> str:
    """If MiniMax returned JSON-wrapped markdown, extract the content."""
    text = text.strip()
    if text.startswith("{") and '"header"' in text:
        try:
            import json as _json
            data = _json.loads(text)
            # Try common key names
            for key in ("header", "content", "text", "memo", "digest"):
                if key in data and isinstance(data[key], str):
                    return data[key]
            # Fallback: join all string values
            parts = [v for v in data.values() if isinstance(v, str)]
            if parts:
                return "\n\n".join(parts)
        except Exception:
            pass
    return text


def get_recent_signals(hours: int = 24) -> list[dict]:
    """Get signals collected within the last N hours from SQLite."""
    store = SignalStore()
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()

    with store._get_conn() as conn:
        rows = conn.execute(
            """
            SELECT * FROM signals
            WHERE collected_at >= ?
            ORDER BY collected_at DESC
            """,
            (cutoff,),
        ).fetchall()
        return [dict(row) for row in rows]


def main() -> int:
    print("=" * 60)
    print("GROWTH OS — DAILY DIGEST")
    print(f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    print("=" * 60)

    # 1. Get recent signals
    signals = get_recent_signals(hours=24)
    print(f"\nSignals in last 24h: {len(signals)}")

    if len(signals) < 3:
        print("Too few signals for digest (need >= 3)")
        return 0

    # 2. Generate digest
    output_dir = get_memo_output_dir()
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    output_path = output_dir / f"daily_digest_{date_str}.md"

    print(f"Generating digest -> {output_path}")

    try:
        engine = DailyDigestEngine()
        result_path = engine.run(signals, output_path)
        print(f"\nDigest generated: {result_path}")

        # Print preview
        content = output_path.read_text()
        print("\n" + "-" * 40)
        print("DIGEST PREVIEW")
        print("-" * 40)
        print(content[:2000])
        if len(content) > 2000:
            print(f"\n... [truncated, full digest at {result_path}]")

        return 0

    except Exception as e:
        print(f"\nDigest generation failed: {e}")
        return 2


if __name__ == "__main__":
    sys.exit(main())
