"""Growth Workflow Intelligence Brief generator.

5-section weekly brief format:
  This week's signal | What changed | Workflow to redesign | Action this week | Thesis update | Prediction to track
"""

from datetime import datetime, timezone
from pathlib import Path

from inference_engines.base import InferenceEngine


BRIEF_PROMPT = """Generate a Growth Workflow Intelligence Brief from the signals below.

Date: {date}

Recent Signals:
{signals_summary}

Active Theses:
{theses}

Predictions:
{predictions}

Output this 6-section format ONLY — no other content:

## This Week's Signal
[One sentence: the single most important signal this week and why it matters for India fintech/embedded lending/GTM]

## What Changed
[3-5 bullet points: what shifted this week vs. last week in specific metrics or patterns. Be concrete, not generic.]

## Workflow to Redesign
[Pick ONE workflow from these 6 options that this signal most directly implies:
crm_segmentation_redesign, retention_escalation, lead_qualification_routing,
campaign_prioritisation, embedded_lending_activation, lifecycle_automation
Fill in: workflow name, before state, after state, decision routing, and Subhajit's reference metric]

## Action This Week
[3 specific actions for the next 7 days. Each starts with a verb. Ground in specific metrics.]

## Strategic Thesis Update
[If any signal confirms, challenges, or updates an existing thesis, say so. If not, write "No thesis update this week." Be specific about which thesis and how.]

## Prediction to Track
[One prediction from the prediction list that this week's signals move closer to resolving. Note: confirmed/invalidated/pending and why.]

---
Generated by Growth Workflow OS · github.com/Das-rebel/growth-workflow-os
"""


class WeeklyMemoEngine(InferenceEngine):
    """Generate 6-section Growth Workflow Intelligence Brief."""

    def __init__(self):
        super().__init__("memo_generation")

    def run(self, signals: list, theses: list, predictions: list, output_path: Path) -> str:
        """Generate the 6-section brief.

        Args:
            signals: Recent signals with interpretations
            theses: Active strategic theses
            predictions: Pending and resolved predictions
            output_path: Where to write the output

        Returns:
            Path to generated file
        """
        # Build signals summary
        signals_summary = []
        for s in signals[:20]:
            weight = s.get("strategic_weight") or 0
            prefix = f"[{weight:.0%}]" if weight else "[     ]"
            signals_summary.append(f"{prefix} {s['text'][:200]}...")
        signals_text = "\n".join(signals_summary) if signals_summary else "No recent signals."

        # Theses summary
        theses_text = "\n".join([f"- {t['thesis_text']}" for t in theses[:8]]) if theses else "No active theses."

        # Predictions summary
        pred_parts = []
        if predictions.get("pending"):
            pred_parts.append("Pending:")
            for p in predictions["pending"][:5]:
                pred_parts.append(f"  - {p['prediction_text']}")
        if predictions.get("resolved"):
            pred_parts.append("Resolved:")
            for p in predictions["resolved"][:3]:
                status = "✓" if p.get("outcome_correct") == "true" else "✗"
                pred_parts.append(f"  {status} {p['prediction_text']}: {p.get('outcome', 'N/A')}")
        predictions_text = "\n".join(pred_parts) if pred_parts else "No predictions."

        system_note = (
            "You are generating a Growth Workflow Intelligence Brief for Subhajit Das, "
            "a fintech growth operator. Write in his voice — specific metrics, India context, "
            "falsifiable claims. Follow the 6-section format exactly. No generic observations."
        )

        prompt = BRIEF_PROMPT.format(
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            signals_summary=signals_text,
            theses=theses_text,
            predictions=predictions_text,
        )

        try:
            memo_text = self.infer(prompt, system_prompt=system_note)
            output_path.write_text(memo_text)
            return str(output_path)
        except Exception as e:
            raise RuntimeError(f"Memo generation failed: {e}")